apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-mctc
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: mctc-workload-1
            url: https://mctc-workload-1-control-plane:6443
  template:
    metadata:
      name: '{{cluster}}-mctc-demo'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/R-Lawton/mctc_phase2-demo.git'
        targetRevision: HEAD
        directory:
          recurse: true    
        path: config/
      destination:
        name: '{{cluster}}'
        namespace: mctc-demo
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true
      